# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sudoku_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 638)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cell11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11.setGeometry(QtCore.QRect(10, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell11.setFont(font)
        self.cell11.setObjectName("cell11")
        self.cell12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12.setGeometry(QtCore.QRect(70, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell12.setFont(font)
        self.cell12.setObjectName("cell12")
        self.cell13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13.setGeometry(QtCore.QRect(130, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell13.setFont(font)
        self.cell13.setObjectName("cell13")
        self.cell14 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell14.setGeometry(QtCore.QRect(190, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell14.setFont(font)
        self.cell14.setObjectName("cell14")
        self.cell16 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell16.setGeometry(QtCore.QRect(310, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell16.setFont(font)
        self.cell16.setObjectName("cell16")
        self.cell15 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell15.setGeometry(QtCore.QRect(250, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell15.setFont(font)
        self.cell15.setObjectName("cell15")
        self.cell17 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell17.setGeometry(QtCore.QRect(370, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell17.setFont(font)
        self.cell17.setObjectName("cell17")
        self.cell18 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell18.setGeometry(QtCore.QRect(430, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell18.setFont(font)
        self.cell18.setObjectName("cell18")
        self.cell19 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell19.setGeometry(QtCore.QRect(490, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell19.setFont(font)
        self.cell19.setObjectName("cell19")
        self.cell24 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell24.setGeometry(QtCore.QRect(190, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell24.setFont(font)
        self.cell24.setObjectName("cell24")
        self.cell28 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell28.setGeometry(QtCore.QRect(430, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell28.setFont(font)
        self.cell28.setObjectName("cell28")
        self.cell27 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell27.setGeometry(QtCore.QRect(370, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell27.setFont(font)
        self.cell27.setObjectName("cell27")
        self.cell21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21.setGeometry(QtCore.QRect(10, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell21.setFont(font)
        self.cell21.setObjectName("cell21")
        self.cell25 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell25.setGeometry(QtCore.QRect(250, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell25.setFont(font)
        self.cell25.setObjectName("cell25")
        self.cell23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23.setGeometry(QtCore.QRect(130, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell23.setFont(font)
        self.cell23.setObjectName("cell23")
        self.cell26 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell26.setGeometry(QtCore.QRect(310, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell26.setFont(font)
        self.cell26.setObjectName("cell26")
        self.cell22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22.setGeometry(QtCore.QRect(70, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell22.setFont(font)
        self.cell22.setObjectName("cell22")
        self.cell29 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell29.setGeometry(QtCore.QRect(490, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell29.setFont(font)
        self.cell29.setObjectName("cell29")
        self.textEdit_19 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_19.setGeometry(QtCore.QRect(190, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_19.setFont(font)
        self.textEdit_19.setObjectName("textEdit_19")
        self.textEdit_20 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_20.setGeometry(QtCore.QRect(430, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_20.setFont(font)
        self.textEdit_20.setObjectName("textEdit_20")
        self.textEdit_21 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_21.setGeometry(QtCore.QRect(370, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_21.setFont(font)
        self.textEdit_21.setObjectName("textEdit_21")
        self.textEdit_22 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_22.setGeometry(QtCore.QRect(10, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_22.setFont(font)
        self.textEdit_22.setObjectName("textEdit_22")
        self.textEdit_23 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_23.setGeometry(QtCore.QRect(250, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_23.setFont(font)
        self.textEdit_23.setObjectName("textEdit_23")
        self.textEdit_24 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_24.setGeometry(QtCore.QRect(130, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_24.setFont(font)
        self.textEdit_24.setObjectName("textEdit_24")
        self.textEdit_25 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_25.setGeometry(QtCore.QRect(310, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_25.setFont(font)
        self.textEdit_25.setObjectName("textEdit_25")
        self.textEdit_26 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_26.setGeometry(QtCore.QRect(70, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_26.setFont(font)
        self.textEdit_26.setObjectName("textEdit_26")
        self.textEdit_27 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_27.setGeometry(QtCore.QRect(490, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_27.setFont(font)
        self.textEdit_27.setObjectName("textEdit_27")
        self.textEdit_28 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_28.setGeometry(QtCore.QRect(190, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_28.setFont(font)
        self.textEdit_28.setObjectName("textEdit_28")
        self.textEdit_29 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_29.setGeometry(QtCore.QRect(430, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_29.setFont(font)
        self.textEdit_29.setObjectName("textEdit_29")
        self.textEdit_30 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_30.setGeometry(QtCore.QRect(370, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_30.setFont(font)
        self.textEdit_30.setObjectName("textEdit_30")
        self.textEdit_31 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_31.setGeometry(QtCore.QRect(10, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_31.setFont(font)
        self.textEdit_31.setObjectName("textEdit_31")
        self.textEdit_32 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_32.setGeometry(QtCore.QRect(250, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_32.setFont(font)
        self.textEdit_32.setObjectName("textEdit_32")
        self.textEdit_33 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_33.setGeometry(QtCore.QRect(130, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_33.setFont(font)
        self.textEdit_33.setObjectName("textEdit_33")
        self.textEdit_34 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_34.setGeometry(QtCore.QRect(310, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_34.setFont(font)
        self.textEdit_34.setObjectName("textEdit_34")
        self.textEdit_35 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_35.setGeometry(QtCore.QRect(70, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_35.setFont(font)
        self.textEdit_35.setObjectName("textEdit_35")
        self.textEdit_36 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_36.setGeometry(QtCore.QRect(490, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_36.setFont(font)
        self.textEdit_36.setObjectName("textEdit_36")
        self.textEdit_37 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_37.setGeometry(QtCore.QRect(190, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_37.setFont(font)
        self.textEdit_37.setObjectName("textEdit_37")
        self.textEdit_38 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_38.setGeometry(QtCore.QRect(430, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_38.setFont(font)
        self.textEdit_38.setObjectName("textEdit_38")
        self.textEdit_39 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_39.setGeometry(QtCore.QRect(370, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_39.setFont(font)
        self.textEdit_39.setObjectName("textEdit_39")
        self.textEdit_40 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_40.setGeometry(QtCore.QRect(10, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_40.setFont(font)
        self.textEdit_40.setObjectName("textEdit_40")
        self.textEdit_41 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_41.setGeometry(QtCore.QRect(250, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_41.setFont(font)
        self.textEdit_41.setObjectName("textEdit_41")
        self.textEdit_42 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_42.setGeometry(QtCore.QRect(130, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_42.setFont(font)
        self.textEdit_42.setObjectName("textEdit_42")
        self.textEdit_43 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_43.setGeometry(QtCore.QRect(310, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_43.setFont(font)
        self.textEdit_43.setObjectName("textEdit_43")
        self.textEdit_44 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_44.setGeometry(QtCore.QRect(70, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_44.setFont(font)
        self.textEdit_44.setObjectName("textEdit_44")
        self.textEdit_45 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_45.setGeometry(QtCore.QRect(490, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_45.setFont(font)
        self.textEdit_45.setObjectName("textEdit_45")
        self.textEdit_46 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_46.setGeometry(QtCore.QRect(190, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_46.setFont(font)
        self.textEdit_46.setObjectName("textEdit_46")
        self.textEdit_47 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_47.setGeometry(QtCore.QRect(430, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_47.setFont(font)
        self.textEdit_47.setObjectName("textEdit_47")
        self.textEdit_48 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_48.setGeometry(QtCore.QRect(370, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_48.setFont(font)
        self.textEdit_48.setObjectName("textEdit_48")
        self.textEdit_49 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_49.setGeometry(QtCore.QRect(10, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_49.setFont(font)
        self.textEdit_49.setObjectName("textEdit_49")
        self.textEdit_50 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_50.setGeometry(QtCore.QRect(250, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_50.setFont(font)
        self.textEdit_50.setObjectName("textEdit_50")
        self.textEdit_51 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_51.setGeometry(QtCore.QRect(130, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_51.setFont(font)
        self.textEdit_51.setObjectName("textEdit_51")
        self.textEdit_52 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_52.setGeometry(QtCore.QRect(310, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_52.setFont(font)
        self.textEdit_52.setObjectName("textEdit_52")
        self.textEdit_53 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_53.setGeometry(QtCore.QRect(70, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_53.setFont(font)
        self.textEdit_53.setObjectName("textEdit_53")
        self.textEdit_54 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_54.setGeometry(QtCore.QRect(490, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_54.setFont(font)
        self.textEdit_54.setObjectName("textEdit_54")
        self.textEdit_55 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_55.setGeometry(QtCore.QRect(190, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_55.setFont(font)
        self.textEdit_55.setObjectName("textEdit_55")
        self.textEdit_56 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_56.setGeometry(QtCore.QRect(430, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_56.setFont(font)
        self.textEdit_56.setObjectName("textEdit_56")
        self.textEdit_57 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_57.setGeometry(QtCore.QRect(370, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_57.setFont(font)
        self.textEdit_57.setObjectName("textEdit_57")
        self.textEdit_58 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_58.setGeometry(QtCore.QRect(10, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_58.setFont(font)
        self.textEdit_58.setObjectName("textEdit_58")
        self.textEdit_59 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_59.setGeometry(QtCore.QRect(250, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_59.setFont(font)
        self.textEdit_59.setObjectName("textEdit_59")
        self.textEdit_60 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_60.setGeometry(QtCore.QRect(130, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_60.setFont(font)
        self.textEdit_60.setObjectName("textEdit_60")
        self.textEdit_61 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_61.setGeometry(QtCore.QRect(310, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_61.setFont(font)
        self.textEdit_61.setObjectName("textEdit_61")
        self.textEdit_62 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_62.setGeometry(QtCore.QRect(70, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_62.setFont(font)
        self.textEdit_62.setObjectName("textEdit_62")
        self.textEdit_63 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_63.setGeometry(QtCore.QRect(490, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_63.setFont(font)
        self.textEdit_63.setObjectName("textEdit_63")
        self.textEdit_64 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_64.setGeometry(QtCore.QRect(190, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_64.setFont(font)
        self.textEdit_64.setObjectName("textEdit_64")
        self.textEdit_65 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_65.setGeometry(QtCore.QRect(430, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_65.setFont(font)
        self.textEdit_65.setObjectName("textEdit_65")
        self.textEdit_66 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_66.setGeometry(QtCore.QRect(370, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_66.setFont(font)
        self.textEdit_66.setObjectName("textEdit_66")
        self.cell41 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell41.setGeometry(QtCore.QRect(10, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell41.setFont(font)
        self.cell41.setObjectName("cell41")
        self.textEdit_68 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_68.setGeometry(QtCore.QRect(250, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_68.setFont(font)
        self.textEdit_68.setObjectName("textEdit_68")
        self.textEdit_69 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_69.setGeometry(QtCore.QRect(130, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_69.setFont(font)
        self.textEdit_69.setObjectName("textEdit_69")
        self.textEdit_70 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_70.setGeometry(QtCore.QRect(310, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_70.setFont(font)
        self.textEdit_70.setObjectName("textEdit_70")
        self.textEdit_71 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_71.setGeometry(QtCore.QRect(70, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_71.setFont(font)
        self.textEdit_71.setObjectName("textEdit_71")
        self.textEdit_72 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_72.setGeometry(QtCore.QRect(490, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.textEdit_72.setFont(font)
        self.textEdit_72.setObjectName("textEdit_72")
        self.cell34 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell34.setGeometry(QtCore.QRect(190, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell34.setFont(font)
        self.cell34.setObjectName("cell34")
        self.cell38 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell38.setGeometry(QtCore.QRect(430, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell38.setFont(font)
        self.cell38.setObjectName("cell38")
        self.cell37 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell37.setGeometry(QtCore.QRect(370, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell37.setFont(font)
        self.cell37.setObjectName("cell37")
        self.cell31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31.setGeometry(QtCore.QRect(10, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell31.setFont(font)
        self.cell31.setObjectName("cell31")
        self.cell35 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell35.setGeometry(QtCore.QRect(250, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell35.setFont(font)
        self.cell35.setObjectName("cell35")
        self.cell33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33.setGeometry(QtCore.QRect(130, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell33.setFont(font)
        self.cell33.setObjectName("cell33")
        self.cell36 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell36.setGeometry(QtCore.QRect(310, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell36.setFont(font)
        self.cell36.setObjectName("cell36")
        self.cell32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32.setGeometry(QtCore.QRect(70, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell32.setFont(font)
        self.cell32.setObjectName("cell32")
        self.cell39 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell39.setGeometry(QtCore.QRect(490, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell39.setFont(font)
        self.cell39.setObjectName("cell39")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 9, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 50, 101, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 50, 101, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuexit = QtWidgets.QMenu(self.menubar)
        self.menuexit.setObjectName("menuexit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuexit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cell11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "SUDOKU"))
        self.pushButton.setText(_translate("MainWindow", "SOLVE"))
        self.pushButton_2.setText(_translate("MainWindow", "GENERATE"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuexit.setTitle(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
